name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Adjust this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: itsbaivab
          password: ALMARISANCHARI

      - name: Build Docker Image
        run: docker build -t itsbaivab/streamlit:latest .
        
      - name: Push Docker Image
        run: docker push itsbaivab/streamlit:latest
