name: Deploy to Azure App Service

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: News-classifire # Replace with your Azure App Service name
          publish-profile: $<publishData><publishProfile profileName="News-classifire - Web Deploy" publishMethod="MSDeploy" publishUrl="news-classifire.scm.azurewebsites.net:443" msdeploySite="News-classifire" userName="$News-classifire" userPWD="tjDbDp6QdWidbsMwcYyWa2HZRZGJ97DfgWHj5H6SQFCgg2xAj7GrTl8AWYez" destinationAppUrl="https://news-classifire.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="News-classifire - FTP" publishMethod="FTP" publishUrl="ftps://waws-prod-blu-493.ftp.azurewebsites.windows.net/site/wwwroot" ftpPassiveMode="True" userName="News-classifire\$News-classifire" userPWD="tjDbDp6QdWidbsMwcYyWa2HZRZGJ97DfgWHj5H6SQFCgg2xAj7GrTl8AWYez" destinationAppUrl="https://news-classifire.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile><publishProfile profileName="News-classifire - Zip Deploy" publishMethod="ZipDeploy" publishUrl="news-classifire.scm.azurewebsites.net:443" userName="$News-classifire" userPWD="tjDbDp6QdWidbsMwcYyWa2HZRZGJ97DfgWHj5H6SQFCgg2xAj7GrTl8AWYez" destinationAppUrl="https://news-classifire.azurewebsites.net" SQLServerDBConnectionString="" mySQLDBConnectionString="" hostingProviderForumLink="" controlPanelLink="http://windows.azure.com" webSystem="WebSites"><databases /></publishProfile></publishData>
          docker-image: itsbaivab/streamlit:latest
